# Generated by Django 5.1.3 on 2024-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='comments', to='hashtags.hashtag'),
        ),
    ]
